pod 'SVProgressHUD', '~> 1.0'
pod 'MagicalRecord', '~> 2.2'
pod 'AFNetworking', '~> 2.2'
pod 'Google-Mobile-Ads-SDK', '~> 6.9.2'
#pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.7'
pod 'XCDYouTubeKit', '~> 2.2'
pod 'dailymotion-player-objc', '~> 2.9'