platform :ios, '7.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.4'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'MagicalRecord', '~> 2.3.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'XCDYouTubeKit', '~> 2.2'
pod 'dailymotion-player-objc', '~> 2.9'
pod 'GoogleAnalytics', '~> 3.13'
pod 'PureLayout', '~> 2.0'
pod 'AFDownloadRequestOperation', '~> 2.0.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'UIView+AnimationExtensions', '~> 1.0'